CREATE TABLE BBS_FILE (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  ORG_FILENAME VARCHAR2(255) NOT NULL,
  SAVE_FILENAME VARCHAR2(255) NOT NULL,
  FILEPATH VARCHAR2(500) NOT NULL,
  FILESIZE NUMBER(20) DEFAULT 0,
  MIMETYPE VARCHAR2(100),
  REGDATE DATE DEFAULT SYSDATE,
  OK NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE BBS_FILE_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBS_FILE_BBSNO ON BBS_FILE(BBSNO);
