CREATE TABLE BBSW (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  PARENT_NO NUMBER(10),
  WRITER VARCHAR2(100) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
  CHILD_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBSW_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBSW_BBSNO ON BBSW(BBSNO);
CREATE INDEX IDX_BBSW_PARENT_NO ON BBSW(PARENT_NO);

COMMIT;
