-- BBS existing-database migration for Oracle XE.
-- Goal: keep existing data, add columns/tables/constraints/indexes needed by current and near-future features.
-- Safe to re-run: each block checks USER_* metadata before applying changes.
-- Current features covered: bcrypt migration, view count, comments/replies, reactions, file upload.

SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'SALT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (SALT VARCHAR2(100))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PASSWORD_ALGO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE LOGIN ADD (PASSWORD_ALGO VARCHAR2(20) DEFAULT 'sha512' NOT NULL)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PASSWORD_UPDATED_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (PASSWORD_UPDATED_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'LOGIN_FAILED_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (LOGIN_FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'LAST_LOGIN_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (LAST_LOGIN_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PHONE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (PHONE VARCHAR2(30))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'OK';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (OK NUMBER(1) DEFAULT 1 NOT NULL)';
  END IF;
END;
/

-- bcrypt hashes are currently 60 chars, but 255 leaves room for future algorithm prefixes.
-- LOGIN.ID is widened to match BBS.WRITER/BBSW.WRITER before writer FKs are added.
ALTER TABLE LOGIN MODIFY (ID VARCHAR2(100));
ALTER TABLE LOGIN MODIFY (PASSWORD VARCHAR2(255));
ALTER TABLE LOGIN MODIFY (SALT NULL);

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBS_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'VIEW_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (VIEW_COUNT NUMBER DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBS_REACTION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_REACTION (
        BBSNO NUMBER(10) NOT NULL,
        USER_ID VARCHAR2(100) NOT NULL,
        REACTION_TYPE VARCHAR2(10) NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATEDATE DATE,
        CONSTRAINT PK_BBS_REACTION PRIMARY KEY (BBSNO, USER_ID),
        CONSTRAINT CK_BBS_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
      )
    ]';
  END IF;
END;
/

ALTER TABLE BBS_REACTION MODIFY (USER_ID VARCHAR2(100));

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'LIKE_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'DISLIKE_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_REACTION_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_REACTION_USER ON BBS_REACTION(USER_ID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBSW';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBSW (
        NO NUMBER(10) PRIMARY KEY,
        BBSNO NUMBER(10) NOT NULL,
        PARENT_NO NUMBER(10),
        WRITER VARCHAR2(100) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
        CHILD_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATEDATE DATE,
        OK NUMBER(1) DEFAULT 1 NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBSW_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBSW_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION ADD CONSTRAINT FK_BBS_REACTION_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION ADD CONSTRAINT FK_BBS_REACTION_LOGIN FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBS_FILE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_FILE (
        NO NUMBER(10) PRIMARY KEY,
        BBSNO NUMBER(10) NOT NULL,
        ORG_FILENAME VARCHAR2(255) NOT NULL,
        SAVE_FILENAME VARCHAR2(255) NOT NULL,
        FILEPATH VARCHAR2(500) NOT NULL,
        FILESIZE NUMBER(20) DEFAULT 0,
        MIMETYPE VARCHAR2(100),
        REGDATE DATE DEFAULT SYSDATE,
        OK NUMBER(1) DEFAULT 1
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBS_FILE_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_FILE_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_OK_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_OK_NO ON BBS(OK, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_WRITER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_WRITER ON BBS(WRITER)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_BBSNO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_BBSNO ON BBSW(BBSNO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_PARENT_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_PARENT_NO ON BBSW(PARENT_NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_WRITER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_WRITER ON BBSW(WRITER)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_FILE_BBSNO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_FILE_BBSNO ON BBS_FILE(BBSNO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_WRITER_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD CONSTRAINT FK_BBS_WRITER_LOGIN FOREIGN KEY (WRITER) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_PARENT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_PARENT FOREIGN KEY (PARENT_NO) REFERENCES BBSW(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_WRITER_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_WRITER_LOGIN FOREIGN KEY (WRITER) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_FILE_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_FILE ADD CONSTRAINT FK_BBS_FILE_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

COMMIT;
