-- BBS existing-database migration for Oracle XE.
-- Goal: keep existing data, add columns/tables/constraints/indexes needed by current and near-future features.
-- Safe to re-run: each block checks USER_* metadata before applying changes.
-- Current features covered: bcrypt migration, view count, comments/replies, reactions, file upload.

SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'SALT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (SALT VARCHAR2(100))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'RESET_TOKEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE RESET_TOKEN (
        NO NUMBER(10) PRIMARY KEY,
        USER_ID VARCHAR2(100) NOT NULL,
        TOKEN VARCHAR2(128) NOT NULL,
        EXPIRES_AT DATE NOT NULL,
        USED NUMBER(1) DEFAULT 0 NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        USEDATE DATE
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'RESET_TOKEN_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE RESET_TOKEN_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBSW_REACTION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBSW_REACTION (
        WNO NUMBER(10) NOT NULL,
        USER_ID VARCHAR2(100) NOT NULL,
        REACTION_TYPE VARCHAR2(10) NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATEDATE DATE,
        CONSTRAINT PK_BBSW_REACTION PRIMARY KEY (WNO, USER_ID),
        CONSTRAINT CK_BBSW_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'UX_RESET_TOKEN_TOKEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_RESET_TOKEN_TOKEN ON RESET_TOKEN(TOKEN)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_RESET_TOKEN_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_RESET_TOKEN_USER ON RESET_TOKEN(USER_ID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_REACTION_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_REACTION_USER ON BBSW_REACTION(USER_ID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_REACTION_WNO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_REACTION_WNO ON BBSW_REACTION(WNO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PASSWORD_ALGO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE LOGIN ADD (PASSWORD_ALGO VARCHAR2(20) DEFAULT 'sha512' NOT NULL)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PASSWORD_UPDATED_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (PASSWORD_UPDATED_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'LOGIN_FAILED_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (LOGIN_FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'LAST_LOGIN_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (LAST_LOGIN_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'PHONE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (PHONE VARCHAR2(30))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'ROLE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE LOGIN ADD (ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL)]';
  END IF;
END;
/

-- Existing sample databases use ID='admin' as the seeded administrator account.
UPDATE LOGIN
SET ROLE = 'ADMIN'
WHERE ID = 'admin'
  AND ROLE <> 'ADMIN';

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'LOGIN'
    AND COLUMN_NAME = 'OK';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (OK NUMBER(1) DEFAULT 1 NOT NULL)';
  END IF;
END;
/

-- bcrypt hashes are currently 60 chars, but 255 leaves room for future algorithm prefixes.
-- LOGIN.ID is widened to match BBS.WRITER/BBSW.WRITER before writer FKs are added.
ALTER TABLE LOGIN MODIFY (ID VARCHAR2(100));
ALTER TABLE LOGIN MODIFY (PASSWORD VARCHAR2(255));
ALTER TABLE LOGIN MODIFY (SALT NULL);

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBS_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'VIEW_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (VIEW_COUNT NUMBER DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBS_REACTION';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_REACTION (
        BBSNO NUMBER(10) NOT NULL,
        USER_ID VARCHAR2(100) NOT NULL,
        REACTION_TYPE VARCHAR2(10) NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATEDATE DATE,
        CONSTRAINT PK_BBS_REACTION PRIMARY KEY (BBSNO, USER_ID),
        CONSTRAINT CK_BBS_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
      )
    ]';
  END IF;
END;
/

ALTER TABLE BBS_REACTION MODIFY (USER_ID VARCHAR2(100));

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'LIKE_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'DISLIKE_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'IS_NOTICE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (IS_NOTICE NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'ADMIN_HIDDEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (ADMIN_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'ADMIN_HIDDEN_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (ADMIN_HIDDEN_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBS'
    AND COLUMN_NAME = 'ADMIN_HIDDEN_BY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (ADMIN_HIDDEN_BY VARCHAR2(100))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_REACTION_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_REACTION_USER ON BBS_REACTION(USER_ID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBSW';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBSW (
        NO NUMBER(10) PRIMARY KEY,
        BBSNO NUMBER(10) NOT NULL,
        PARENT_NO NUMBER(10),
        WRITER VARCHAR2(100) NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
        CHILD_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        ADMIN_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL,
        ADMIN_HIDDEN_AT DATE,
        ADMIN_HIDDEN_BY VARCHAR2(100),
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATEDATE DATE,
        OK NUMBER(1) DEFAULT 1 NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBSW'
    AND COLUMN_NAME = 'ADMIN_HIDDEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD (ADMIN_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBSW'
    AND COLUMN_NAME = 'ADMIN_HIDDEN_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD (ADMIN_HIDDEN_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'BBSW'
    AND COLUMN_NAME = 'ADMIN_HIDDEN_BY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD (ADMIN_HIDDEN_BY VARCHAR2(100))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBSW_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBSW_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION ADD CONSTRAINT FK_BBS_REACTION_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_REACTION_COMMENT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW_REACTION ADD CONSTRAINT FK_BBSW_REACTION_COMMENT FOREIGN KEY (WNO) REFERENCES BBSW(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_REACTION_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW_REACTION ADD CONSTRAINT FK_BBSW_REACTION_LOGIN FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION ADD CONSTRAINT FK_BBS_REACTION_LOGIN FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'BBS_FILE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_FILE (
        NO NUMBER(10) PRIMARY KEY,
        BBSNO NUMBER(10) NOT NULL,
        ORG_FILENAME VARCHAR2(255) NOT NULL,
        SAVE_FILENAME VARCHAR2(255) NOT NULL,
        FILEPATH VARCHAR2(500) NOT NULL,
        FILESIZE NUMBER(20) DEFAULT 0,
        MIMETYPE VARCHAR2(100),
        REGDATE DATE DEFAULT SYSDATE,
        OK NUMBER(1) DEFAULT 1
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_SEQUENCES
  WHERE SEQUENCE_NAME = 'BBS_FILE_SEQ';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_FILE_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_OK_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_OK_NO ON BBS(OK, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_WRITER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_WRITER ON BBS(WRITER)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_NOTICE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_NOTICE ON BBS(OK, IS_NOTICE, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_ADMIN_HIDDEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_ADMIN_HIDDEN ON BBS(OK, ADMIN_HIDDEN, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_BBSNO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_BBSNO ON BBSW(BBSNO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_ADMIN_HIDDEN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_ADMIN_HIDDEN ON BBSW(BBSNO, ADMIN_HIDDEN)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_PARENT_NO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_PARENT_NO ON BBSW(PARENT_NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_WRITER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBSW_WRITER ON BBSW(WRITER)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_FILE_BBSNO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_FILE_BBSNO ON BBS_FILE(BBSNO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_WRITER_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD CONSTRAINT FK_BBS_WRITER_LOGIN FOREIGN KEY (WRITER) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_PARENT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_PARENT FOREIGN KEY (PARENT_NO) REFERENCES BBSW(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_WRITER_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW ADD CONSTRAINT FK_BBSW_WRITER_LOGIN FOREIGN KEY (WRITER) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_FILE_BBS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_FILE ADD CONSTRAINT FK_BBS_FILE_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_RESET_TOKEN_LOGIN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RESET_TOKEN ADD CONSTRAINT FK_RESET_TOKEN_LOGIN FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'NICKNAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (NICKNAME VARCHAR2(80))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'BIO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (BIO VARCHAR2(500))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'AVATAR_URL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (AVATAR_URL VARCHAR2(500))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'USER_STATUS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE LOGIN ADD (USER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'SUSPENDED_AT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (SUSPENDED_AT DATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'SUSPENDED_BY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (SUSPENDED_BY VARCHAR2(100))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LOGIN' AND COLUMN_NAME = 'SUSPEND_REASON';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LOGIN ADD (SUSPEND_REASON VARCHAR2(500))';
  END IF;
END;
/

UPDATE LOGIN SET NICKNAME = NAME WHERE NICKNAME IS NULL;
UPDATE LOGIN SET USER_STATUS = 'ACTIVE' WHERE USER_STATUS IS NULL;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'BBS_CATEGORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_CATEGORY (
        ID NUMBER(10) PRIMARY KEY,
        NAME VARCHAR2(80) NOT NULL,
        SLUG VARCHAR2(40) NOT NULL,
        DISPLAY_ORDER NUMBER(10) DEFAULT 100 NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT UX_BBS_CATEGORY_SLUG UNIQUE (SLUG)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'BBS_CATEGORY_SEQ';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_CATEGORY_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

MERGE INTO BBS_CATEGORY C
USING (SELECT '자유' AS NAME, 'free' AS SLUG, 10 AS DISPLAY_ORDER FROM DUAL) S
ON (C.SLUG = S.SLUG)
WHEN NOT MATCHED THEN
  INSERT (ID, NAME, SLUG, DISPLAY_ORDER, IS_ACTIVE, REGDATE)
  VALUES (BBS_CATEGORY_SEQ.NEXTVAL, S.NAME, S.SLUG, S.DISPLAY_ORDER, 1, SYSDATE);

MERGE INTO BBS_CATEGORY C
USING (SELECT '공지' AS NAME, 'notice' AS SLUG, 20 AS DISPLAY_ORDER FROM DUAL) S
ON (C.SLUG = S.SLUG)
WHEN NOT MATCHED THEN
  INSERT (ID, NAME, SLUG, DISPLAY_ORDER, IS_ACTIVE, REGDATE)
  VALUES (BBS_CATEGORY_SEQ.NEXTVAL, S.NAME, S.SLUG, S.DISPLAY_ORDER, 1, SYSDATE);

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BBS' AND COLUMN_NAME = 'CATEGORY_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD (CATEGORY_ID NUMBER(10))';
  END IF;
END;
/

UPDATE BBS
SET CATEGORY_ID = (SELECT ID FROM BBS_CATEGORY WHERE SLUG = 'free')
WHERE CATEGORY_ID IS NULL;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BBS_CATEGORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_CATEGORY ON BBS(CATEGORY_ID, OK, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'BBS_BOOKMARK';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_BOOKMARK (
        BBSNO NUMBER(10) NOT NULL,
        USER_ID VARCHAR2(100) NOT NULL,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_BBS_BOOKMARK PRIMARY KEY (BBSNO, USER_ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BBS_BOOKMARK_USER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_BOOKMARK_USER ON BBS_BOOKMARK(USER_ID, REGDATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'BBS_REPORT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BBS_REPORT (
        NO NUMBER(10) PRIMARY KEY,
        TARGET_TYPE VARCHAR2(20) NOT NULL,
        TARGET_ID NUMBER(10) NOT NULL,
        REPORTER_ID VARCHAR2(100) NOT NULL,
        REASON_CODE VARCHAR2(20) NOT NULL,
        REASON_TEXT VARCHAR2(1000),
        STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
        HANDLED_BY VARCHAR2(100),
        HANDLED_AT DATE,
        REGDATE DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT CK_BBS_REPORT_TARGET CHECK (TARGET_TYPE IN ('POST', 'COMMENT')),
        CONSTRAINT CK_BBS_REPORT_REASON CHECK (REASON_CODE IN ('SPAM', 'ABUSE', 'ILLEGAL', 'ETC')),
        CONSTRAINT CK_BBS_REPORT_STATUS CHECK (STATUS IN ('PENDING', 'REJECTED', 'HIDDEN', 'RESOLVED')),
        CONSTRAINT UX_BBS_REPORT_ONE UNIQUE (TARGET_TYPE, TARGET_ID, REPORTER_ID)
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'BBS_REPORT_SEQ';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE BBS_REPORT_SEQ START WITH 1 INCREMENT BY 1';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_BBS_REPORT_STATUS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BBS_REPORT_STATUS ON BBS_REPORT(STATUS, NO)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_BBS_CATEGORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS ADD CONSTRAINT FK_BBS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES BBS_CATEGORY(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_BBS_BOOKMARK_BBS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_BOOKMARK ADD CONSTRAINT FK_BBS_BOOKMARK_BBS FOREIGN KEY (BBSNO) REFERENCES BBS(NO) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_BBS_BOOKMARK_LOGIN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_BOOKMARK ADD CONSTRAINT FK_BBS_BOOKMARK_LOGIN FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_BBS_REPORT_LOGIN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REPORT ADD CONSTRAINT FK_BBS_REPORT_LOGIN FOREIGN KEY (REPORTER_ID) REFERENCES LOGIN(ID) ENABLE NOVALIDATE';
  END IF;
END;
/

COMMIT;
