-- Rollback companion for scripts/migration.sql.
-- This file intentionally avoids DROP TABLE and avoids deleting table rows.
-- Columns added by migration.sql are left in place because dropping columns would delete stored data.

SET DEFINE OFF;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_LOGIN';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION DROP CONSTRAINT FK_BBS_REACTION_LOGIN';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_REACTION_BBS';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_REACTION DROP CONSTRAINT FK_BBS_REACTION_BBS';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_FILE_BBS';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS_FILE DROP CONSTRAINT FK_BBS_FILE_BBS';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_WRITER_LOGIN';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW DROP CONSTRAINT FK_BBSW_WRITER_LOGIN';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_PARENT';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW DROP CONSTRAINT FK_BBSW_PARENT';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBSW_BBS';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBSW DROP CONSTRAINT FK_BBSW_BBS';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_BBS_WRITER_LOGIN';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BBS DROP CONSTRAINT FK_BBS_WRITER_LOGIN';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_REACTION_USER';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBS_REACTION_USER';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_FILE_BBSNO';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBS_FILE_BBSNO';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_WRITER';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBSW_WRITER';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_PARENT_NO';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBSW_PARENT_NO';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBSW_BBSNO';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBSW_BBSNO';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_WRITER';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBS_WRITER';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_BBS_OK_NO';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BBS_OK_NO';
  END IF;
END;
/

-- Non-destructive rollback boundary:
-- The following objects may have been created by migration.sql but are intentionally preserved:
-- LOGIN.SALT, LOGIN.PASSWORD_ALGO, LOGIN.PASSWORD_UPDATED_AT, LOGIN.LOGIN_FAILED_COUNT, LOGIN.LAST_LOGIN_AT
-- BBS.VIEW_COUNT, BBS.LIKE_COUNT, BBS.DISLIKE_COUNT
-- BBS_REACTION
-- BBSW, BBSW_SEQ
-- BBS_FILE, BBS_FILE_SEQ
-- Keeping them preserves existing data and satisfies the "DROP TABLE 금지 / 기존 데이터 삭제 금지" rule.

COMMIT;
