-- BBS 신규 OracleDB 스키마.
-- 기존 DB에는 이 파일 대신 scripts/migration.sql을 사용한다.
-- 비밀번호는 신규 계정 기준 bcrypt 저장을 전제로 한다.

CREATE TABLE LOGIN (
  ID VARCHAR2(100) PRIMARY KEY,
  PASSWORD VARCHAR2(255) NOT NULL,
  SALT VARCHAR2(100),
  PASSWORD_ALGO VARCHAR2(20) DEFAULT 'bcrypt' NOT NULL,
  PASSWORD_UPDATED_AT DATE,
  LOGIN_FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LAST_LOGIN_AT DATE,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(200),
  PHONE VARCHAR2(30),
  NICKNAME VARCHAR2(80),
  BIO VARCHAR2(500),
  AVATAR_URL VARCHAR2(500),
  ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
  USER_STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  SUSPENDED_AT DATE,
  SUSPENDED_BY VARCHAR2(100),
  SUSPEND_REASON VARCHAR2(500),
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE BBS_CATEGORY (
  ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(80) NOT NULL,
  SLUG VARCHAR2(40) NOT NULL,
  DISPLAY_ORDER NUMBER(10) DEFAULT 100 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT UX_BBS_CATEGORY_SLUG UNIQUE (SLUG)
);

CREATE SEQUENCE BBS_CATEGORY_SEQ
  START WITH 1
  INCREMENT BY 1;

INSERT INTO BBS_CATEGORY(ID, NAME, SLUG, DISPLAY_ORDER, IS_ACTIVE, REGDATE)
VALUES(BBS_CATEGORY_SEQ.NEXTVAL, '자유', 'free', 10, 1, SYSDATE);

INSERT INTO BBS_CATEGORY(ID, NAME, SLUG, DISPLAY_ORDER, IS_ACTIVE, REGDATE)
VALUES(BBS_CATEGORY_SEQ.NEXTVAL, '공지', 'notice', 20, 1, SYSDATE);

CREATE TABLE BBS (
  NO NUMBER PRIMARY KEY,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  WRITER VARCHAR2(100) NOT NULL,
  CATEGORY_ID NUMBER(10),
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
  LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  IS_NOTICE NUMBER(1) DEFAULT 0 NOT NULL,
  ADMIN_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL,
  ADMIN_HIDDEN_AT DATE,
  ADMIN_HIDDEN_BY VARCHAR2(100),
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE INDEX IDX_BBS_OK_NO ON BBS(OK, NO);
CREATE INDEX IDX_BBS_NOTICE ON BBS(OK, IS_NOTICE, NO);
CREATE INDEX IDX_BBS_ADMIN_HIDDEN ON BBS(OK, ADMIN_HIDDEN, NO);
CREATE INDEX IDX_BBS_WRITER ON BBS(WRITER);
CREATE INDEX IDX_BBS_CATEGORY ON BBS(CATEGORY_ID, OK, NO);

CREATE TABLE BBSW (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  PARENT_NO NUMBER(10),
  WRITER VARCHAR2(100) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
  CHILD_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  ADMIN_HIDDEN NUMBER(1) DEFAULT 0 NOT NULL,
  ADMIN_HIDDEN_AT DATE,
  ADMIN_HIDDEN_BY VARCHAR2(100),
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBSW_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBSW_BBSNO ON BBSW(BBSNO);
CREATE INDEX IDX_BBSW_ADMIN_HIDDEN ON BBSW(BBSNO, ADMIN_HIDDEN);
CREATE INDEX IDX_BBSW_PARENT_NO ON BBSW(PARENT_NO);
CREATE INDEX IDX_BBSW_WRITER ON BBSW(WRITER);

CREATE TABLE BBS_REACTION (
  BBSNO NUMBER(10) NOT NULL,
  USER_ID VARCHAR2(100) NOT NULL,
  REACTION_TYPE VARCHAR2(10) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  CONSTRAINT PK_BBS_REACTION PRIMARY KEY (BBSNO, USER_ID),
  CONSTRAINT CK_BBS_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX IDX_BBS_REACTION_USER ON BBS_REACTION(USER_ID);

CREATE TABLE BBSW_REACTION (
  WNO NUMBER(10) NOT NULL,
  USER_ID VARCHAR2(100) NOT NULL,
  REACTION_TYPE VARCHAR2(10) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  CONSTRAINT PK_BBSW_REACTION PRIMARY KEY (WNO, USER_ID),
  CONSTRAINT CK_BBSW_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX IDX_BBSW_REACTION_USER ON BBSW_REACTION(USER_ID);
CREATE INDEX IDX_BBSW_REACTION_WNO ON BBSW_REACTION(WNO);

CREATE TABLE BBS_BOOKMARK (
  BBSNO NUMBER(10) NOT NULL,
  USER_ID VARCHAR2(100) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_BBS_BOOKMARK PRIMARY KEY (BBSNO, USER_ID)
);

CREATE INDEX IDX_BBS_BOOKMARK_USER ON BBS_BOOKMARK(USER_ID, REGDATE);

CREATE TABLE BBS_REPORT (
  NO NUMBER(10) PRIMARY KEY,
  TARGET_TYPE VARCHAR2(20) NOT NULL,
  TARGET_ID NUMBER(10) NOT NULL,
  REPORTER_ID VARCHAR2(100) NOT NULL,
  REASON_CODE VARCHAR2(20) NOT NULL,
  REASON_TEXT VARCHAR2(1000),
  STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  HANDLED_BY VARCHAR2(100),
  HANDLED_AT DATE,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT CK_BBS_REPORT_TARGET CHECK (TARGET_TYPE IN ('POST', 'COMMENT')),
  CONSTRAINT CK_BBS_REPORT_REASON CHECK (REASON_CODE IN ('SPAM', 'ABUSE', 'ILLEGAL', 'ETC')),
  CONSTRAINT CK_BBS_REPORT_STATUS CHECK (STATUS IN ('PENDING', 'REJECTED', 'HIDDEN', 'RESOLVED')),
  CONSTRAINT UX_BBS_REPORT_ONE UNIQUE (TARGET_TYPE, TARGET_ID, REPORTER_ID)
);

CREATE SEQUENCE BBS_REPORT_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBS_REPORT_STATUS ON BBS_REPORT(STATUS, NO);
CREATE INDEX IDX_BBS_REPORT_REPORTER ON BBS_REPORT(REPORTER_ID);

CREATE TABLE BBS_FILE (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  ORG_FILENAME VARCHAR2(255) NOT NULL,
  SAVE_FILENAME VARCHAR2(255) NOT NULL,
  FILEPATH VARCHAR2(500) NOT NULL,
  FILESIZE NUMBER(20) DEFAULT 0,
  MIMETYPE VARCHAR2(100),
  REGDATE DATE DEFAULT SYSDATE,
  OK NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE BBS_FILE_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBS_FILE_BBSNO ON BBS_FILE(BBSNO);

CREATE TABLE RESET_TOKEN (
  NO NUMBER(10) PRIMARY KEY,
  USER_ID VARCHAR2(100) NOT NULL,
  TOKEN VARCHAR2(128) NOT NULL,
  EXPIRES_AT DATE NOT NULL,
  USED NUMBER(1) DEFAULT 0 NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  USEDATE DATE
);

CREATE SEQUENCE RESET_TOKEN_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE UNIQUE INDEX UX_RESET_TOKEN_TOKEN ON RESET_TOKEN(TOKEN);
CREATE INDEX IDX_RESET_TOKEN_USER ON RESET_TOKEN(USER_ID);

ALTER TABLE BBS
  ADD CONSTRAINT FK_BBS_WRITER_LOGIN
  FOREIGN KEY (WRITER) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS
  ADD CONSTRAINT FK_BBS_CATEGORY
  FOREIGN KEY (CATEGORY_ID) REFERENCES BBS_CATEGORY(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_PARENT
  FOREIGN KEY (PARENT_NO) REFERENCES BBSW(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_WRITER_LOGIN
  FOREIGN KEY (WRITER) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_REACTION
  ADD CONSTRAINT FK_BBS_REACTION_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_REACTION
  ADD CONSTRAINT FK_BBS_REACTION_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW_REACTION
  ADD CONSTRAINT FK_BBSW_REACTION_COMMENT
  FOREIGN KEY (WNO) REFERENCES BBSW(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW_REACTION
  ADD CONSTRAINT FK_BBSW_REACTION_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_BOOKMARK
  ADD CONSTRAINT FK_BBS_BOOKMARK_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_BOOKMARK
  ADD CONSTRAINT FK_BBS_BOOKMARK_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_REPORT
  ADD CONSTRAINT FK_BBS_REPORT_LOGIN
  FOREIGN KEY (REPORTER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_FILE
  ADD CONSTRAINT FK_BBS_FILE_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE RESET_TOKEN
  ADD CONSTRAINT FK_RESET_TOKEN_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;
