CREATE TABLE LOGIN (
  ID VARCHAR2(50) PRIMARY KEY,
  PASSWORD VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(200),
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE BBS (
  NO NUMBER PRIMARY KEY,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  WRITER VARCHAR2(100) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
