-- BBS 신규 OracleDB 스키마.
-- 기존 DB에는 이 파일 대신 scripts/migration.sql을 사용한다.
-- 비밀번호는 신규 계정 기준 bcrypt 저장을 전제로 한다.

CREATE TABLE LOGIN (
  ID VARCHAR2(100) PRIMARY KEY,
  PASSWORD VARCHAR2(255) NOT NULL,
  SALT VARCHAR2(100),
  PASSWORD_ALGO VARCHAR2(20) DEFAULT 'bcrypt' NOT NULL,
  PASSWORD_UPDATED_AT DATE,
  LOGIN_FAILED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LAST_LOGIN_AT DATE,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(200),
  PHONE VARCHAR2(30),
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE BBS (
  NO NUMBER PRIMARY KEY,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  WRITER VARCHAR2(100) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
  LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE INDEX IDX_BBS_OK_NO ON BBS(OK, NO);
CREATE INDEX IDX_BBS_WRITER ON BBS(WRITER);

CREATE TABLE BBSW (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  PARENT_NO NUMBER(10),
  WRITER VARCHAR2(100) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  DEPTH NUMBER(3) DEFAULT 0 NOT NULL,
  CHILD_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  DISLIKE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  OK NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BBSW_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBSW_BBSNO ON BBSW(BBSNO);
CREATE INDEX IDX_BBSW_PARENT_NO ON BBSW(PARENT_NO);
CREATE INDEX IDX_BBSW_WRITER ON BBSW(WRITER);

CREATE TABLE BBS_REACTION (
  BBSNO NUMBER(10) NOT NULL,
  USER_ID VARCHAR2(100) NOT NULL,
  REACTION_TYPE VARCHAR2(10) NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATEDATE DATE,
  CONSTRAINT PK_BBS_REACTION PRIMARY KEY (BBSNO, USER_ID),
  CONSTRAINT CK_BBS_REACTION_TYPE CHECK (REACTION_TYPE IN ('LIKE', 'DISLIKE'))
);

CREATE INDEX IDX_BBS_REACTION_USER ON BBS_REACTION(USER_ID);

CREATE TABLE BBS_FILE (
  NO NUMBER(10) PRIMARY KEY,
  BBSNO NUMBER(10) NOT NULL,
  ORG_FILENAME VARCHAR2(255) NOT NULL,
  SAVE_FILENAME VARCHAR2(255) NOT NULL,
  FILEPATH VARCHAR2(500) NOT NULL,
  FILESIZE NUMBER(20) DEFAULT 0,
  MIMETYPE VARCHAR2(100),
  REGDATE DATE DEFAULT SYSDATE,
  OK NUMBER(1) DEFAULT 1
);

CREATE SEQUENCE BBS_FILE_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE INDEX IDX_BBS_FILE_BBSNO ON BBS_FILE(BBSNO);

CREATE TABLE RESET_TOKEN (
  NO NUMBER(10) PRIMARY KEY,
  USER_ID VARCHAR2(100) NOT NULL,
  TOKEN VARCHAR2(128) NOT NULL,
  EXPIRES_AT DATE NOT NULL,
  USED NUMBER(1) DEFAULT 0 NOT NULL,
  REGDATE DATE DEFAULT SYSDATE NOT NULL,
  USEDATE DATE
);

CREATE SEQUENCE RESET_TOKEN_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE UNIQUE INDEX UX_RESET_TOKEN_TOKEN ON RESET_TOKEN(TOKEN);
CREATE INDEX IDX_RESET_TOKEN_USER ON RESET_TOKEN(USER_ID);

ALTER TABLE BBS
  ADD CONSTRAINT FK_BBS_WRITER_LOGIN
  FOREIGN KEY (WRITER) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_PARENT
  FOREIGN KEY (PARENT_NO) REFERENCES BBSW(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBSW
  ADD CONSTRAINT FK_BBSW_WRITER_LOGIN
  FOREIGN KEY (WRITER) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_REACTION
  ADD CONSTRAINT FK_BBS_REACTION_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_REACTION
  ADD CONSTRAINT FK_BBS_REACTION_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;

ALTER TABLE BBS_FILE
  ADD CONSTRAINT FK_BBS_FILE_BBS
  FOREIGN KEY (BBSNO) REFERENCES BBS(NO)
  ENABLE NOVALIDATE;

ALTER TABLE RESET_TOKEN
  ADD CONSTRAINT FK_RESET_TOKEN_LOGIN
  FOREIGN KEY (USER_ID) REFERENCES LOGIN(ID)
  ENABLE NOVALIDATE;
